# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/refs/heads/master/schema/config.json
---
customCommands:
  - key: <c-u>
    description: Pick AI commit
    context: files
    prompts:
      - type: menuFromCommand
        title: Select AI Commit Message
        key: CommitMsg
        command: "bash -c '~/.config/lazygit/lazycommit/copilot/ai_commit.sh'"
    command: "~/.config/lazygit/lazycommit/commit_wrapper.sh \"{{.Form.CommitMsg}}\""
    output: terminal
    loadingText: "Generating AI commit messages with GitHub Copilot"

  - key: "<c-g>"
    context: "global"
    description: "GitHub Copilot"
    prompts:
      - type: "menu"
        key: "CopilotAction"
        title: "GitHub Copilot"
        options:
          - name: "Check Status"
            description: "Show current authentication status"
            value: "status"
          - name: "Login"
            description: "Start authentication flow"
            value: "login"
          - name: "Complete Login"
            description: "Complete authentication after entering device code"
            value: "complete"
          - name: "Logout"
            description: "Clear authentication data"
            value: "logout"
          - name: "Test"
            description: "Test current authentication"
            value: "test"
    command: "bash -c '~/.config/lazygit/lazycommit/copilot/copilot.sh {{.Form.CopilotAction}}'"
    output: "popup"
    loadingText: "Processing GitHub Copilot..."

  - key: "<c-n>"
    context: "global"
    description: "Select AI Model"
    prompts:
      - type: "menuFromCommand"
        key: "SelectedModel"
        title: "Choose AI Model"
        command: "bash -c '~/.config/lazygit/lazycommit/copilot/models.sh menu'"
      - type: "confirm"
        key: "Confirm"
        title: "Set Model"
        body: "Set AI model to: {{.Form.SelectedModel}}?"
    command: 'bash -c ''~/.config/lazygit/lazycommit/copilot/models.sh set "{{.Form.SelectedModel}}"'''
    output: "popup"
    loadingText: "Setting AI model..."
